#!/bin/bash
python3 -m openrlhf.cli.train_ppo_ray \
   --ref_num_nodes 1 \
   --ref_num_gpus_per_node 2 \
   --reward_num_nodes 1 \
   --reward_num_gpus_per_node 2 \
   --critic_num_nodes 1 \
   --critic_num_gpus_per_node 2 \
   --actor_num_nodes 1 \
   --actor_num_gpus_per_node 2 \
   --vllm_num_engines 2 \
   --vllm_tensor_parallel_size 2 \
   --colocate_critic_reward \
   --colocate_actor_ref \
   --ref_reward_offload \
   --pretrain /mnt/bs_fs/models/CodeLlama-7b-hf/ \
   --reward_pretrain /mnt/bs_fs/models/CodeLlama-7b-hf/ \
   --micro_train_batch_size 4 \
   --critic_micro_train_batch_size 4 \
   --train_batch_size 8 \
   --micro_rollout_batch_size 32 \
   --rollout_batch_size 64 \
   --prompt_max_len 1024 \
   --generate_max_len 1024 \
   --zero_stage 3 \
   --init_kl_coef 0.01 \
   --normalize_reward \
   --adam_offload \
   --flash_attn \
   --gradient_checkpointing
